### ISSUE TITLE
Super Mario All-Stars + World no longer able to properly load SRAM?

### ISSUE THREAD

**Issue by admonished** [Ramsis-SNES/snes-powerpak-firmware-v3#1]
1. Updated my PowerPak to MUFASA build 11310 from SIMBA
2. To make sure games save properly, I loaded Super Mario All-Stars + Super Mario World (U) [!].smc
3. My SMW data with 47 exits complete was there, so it loaded the .srm fine. I then started a new SMW game in the second slot and saved it
4. Held reset on SNES, saved SRAM, started the game again
5. None of my progress is there, it's as if the game started with a blank .srm (Just a note: I copied the contents my CF card to my computer before updating, so at least it was backed up)

I tried a couple other games and they were able to load-save-load fine, like Super Metroid, A Link to the Past, and Return To Dinosaur Land (hack of SMW). The first two were easy to verify because I could just use the in-game copy feature to copy data to another slot, save SRAM, and load again and see the data I copied on the game's menu. For the SMW hack I beat a level and saved. I'll see what happens with the original version of All-Stars (without SMW included) after I post this.

So hopefully this issue only applies to All-Stars + World? Although it worked fine on SIMBA.

I'm not sure how it initally loaded my "47 exit" data in All-Stars + World, because now I can't get the game to start with anything other than a clean slate. I've reproduced the problem several times by doing this:
1.  Start Super Mario All-Stars + Super Mario World (U) [!].smc (I've also tried renaming the .smc and .srm to "Super Mario All Stars and World (U) [!]" but it made no difference)
2.  Start a new game of Mario 3 and immediately save and exit
3.  Reset SNES, save SRAM — At this point I **know** it has saved properly because I checked and loaded the .srm file in an emulator on my PC and it has the Mario 3 data that I saved on the PowerPak.
4.  Start the .smc on the PowerPak again. Completely blank, no Mario 3 data

I could hold select when loading the game and give you the error log I guess. If I can't solve this I'd rather figure out a way to downgrade back to SIMBA because I never had any problems saving/loading games in that version...

Thanks for all your hard work on your PowerPak firmware!

**Comment by Ramsis-SNES** [comment]
Thank you for reporting this. Hmm, not sure where to start troubleshooting this. First of all, have you checked the file system of your CF card for errors? If it's good, please download the [latest build](https://github.com/Ramsis-SNES/snes-powerpak-firmware-v3/blob/master/src/out/POWERPAK/UPDATE.ROM?raw=true) #11331 and install it by following these steps:
- Copy the UPDATE.ROM file you downloaded to the POWERPAK folder on your CF card, overwriting the existing file.
- Start up your PowerPak, go to the settings menu, and select "Check for firmware update".
- Follow the on-screen instructions.
- After the update process has finished (i.e., the PowerPak intro screen appears), **power-cycle your SNES**.

Then, try again with Super Mario Allstars + World and report back how it works. The reasoning behind all this is that previous builds had a bug that prevented several games from working properly, possibly affecting this game too. ;)

**Comment by admonished** [comment]
Thanks for the quick response. I updated to build #11331 and it seems to be fixed. I'll let you know if I have any issues later on.

Thanks again. (Now the cursor position is saved when backing out of folders!)

**Comment by Ramsis-SNES** [comment]
Thank you too, glad it seems to have worked out for you. :D

> Now the cursor position is saved when backing out of folders!

Yes, the latest build features a couple of usability improvements as well. ;-)
